### ISSUE TITLE
{Suggestions / Discussion}

### ISSUE THREAD

**Issue by togera13** [SodiumZH/Days-with-Monster-Girls#10]
### In regard to preventing mob armies ###
-Why not add a cooldown after successfully taming a mob? You could make it easier to tame without the consequence of them building up quickly.
-What if we limited how many mobs could follow at once? So, you can have as many as you like wandering at home but can only have a (configurable?) amount following you at once.
-What if you made repeated gifts of the same kind have reduced effectiveness? Thus forcing them to either wait longer to keep giving it the same item or to give a different gift from time to time, thus removing the easily abused low end items & giving more value to the high end items as a cooldown remover.
-What if we made affinity gain & experience gain spread amongst the currently following mobs? So that if you bring one mob it will quickly increase, but if you bring multiple mobs it will have reduced reward?
-What if you gave the mobs some buffs or unique effects when you have 3 or less following you? To improve their individuality & promote less is more?

Without some form of restriction people can currently build up mob armies if they have the right materials & go to the right mobs, since certain mobs are easier & faster to tame than others. This is more notable at end game if playing with other mods, as most mods give easy access to certain high-end materials by the end, so mob armies are still possible for those with the wealth to burn.

It is also notable that the current method of preventing mob armies only makes _taming a single mob_ take longer whereas you can still batch tame all at once, thus it does not actually prevent mob armies since you can have multiple trapped mobs at once & just work on all of them to be more time effective. In other words, the current systems punish those who want to tame & have one specific mob, while those just building up a cheap army can still do it by working on multiple mobs at once. (Implying they have the tools necessary to trap & nametag all the mobs close to each other, with mods like Carryon this is easy to do though.)

I would imagine things probably go one of three ways with the current system:
-1 heavily equipped mob. Since you only have the space to carry a little over ~8 items on average when adventuring, because yes you probably are going to have to pick its gear up since it _will_ die if you aren't constantly healing it.
or
-multiple mobs with no equipment. Since carrying more than one mobs equipment isn't all that doable, & the mobs lose experience & affinity when they die so why bother to give them equipment unless you just have hand me downs you are okay with losing. Placing an orb back down is a lot easier than trying to re-equip your mob on the fly.
or
-multiple mobs that can wear armor all wearing cheap hand me downs because of things like Create (mod), ProjectE (mod), Epic Knights (mod), Enemy Expansion (mod), LootR (mod), vanilla mob armor drops, etc. If they lose armor you got for practically free who cares?
...
I am playing on a heavily modded & hard setup so for vanilla the mobs are probably okay in terms of health & damage albeit tedious to tame & healing items for some may be hard to come by, just never expect to bring them with to the deep dark, nether, or end without a casualty.
...
If the mob army makers are patient enough one could easily build a mob army & instead of going without preperation, they could just make a cow, pig, sheep, or chicken farm & have all their mobs farm experience from defeating animals, so mob armies are doable. But anyone that just wants to be able to take a few mobs on an adventure they feel punished as the affinity & level drops are too brutal for the mobs to be useful for anything other than housesitting unless you are okay with respawning & re-equipping them all the time; I mean either that or be prepared to grind xp in your farms & make some very expensive gear for a mob that can't hold their own against most modded mobs...

### Taming ###
-I think some item values should be adjusted to better reflect the effort necessary to get said items. I do not think that iron should have nearly equal weight to diamonds.
-A progress bar or progress text when clicking on or giving an item to a tameable mob would be highly appreciated for those mobs that just take a long time. It would make things much nicer in multiplayer, so we don't sit around trying to tame one when someone wants backup on their adventure & they are waiting for their pal. (We opt for name tagging & caging them now whenever we are trying to go somewhere, but this would be a helpful feature.)

Most people use the Create mod which adds a lot of automatable things one of which is iron, & gold generation, so taming stuff like the Kobold isn't hard so much as a chore from how much iron you will be throwing at it. Same goes for those using stuff like ProjectE, LootR, Etc, as certain materials aren't that hard to get, but others are, yet the current taming process values the expensive stuff nearly the same as the cheap / common stuff in most cases.

### Combat ###
-Mobs lose levels when they die, which makes bringing a single mob with you not worth it, or rather it promotes having them house sitting (using them as guards for your property) rather than having any sort of backup or assistance while adventuring.
-Mobs lose affinity even when it isn't your fault that they died (IE Guard Villagers, etc.) thus making it not really worthwhile to bring the mobs anywhere other than your main base since long distance travel won't be a thing as they don't long distance teleport when "angry".
-Mobs die too easily lending to the prior issues.
-I personally think it would be nice if Creeper girls for instance had blast immunity or at the very least blast resistance, so they aren't easily killed by their fellow creepers.
-A more consistent means of healing certain mobs would be nice, as it stands brewing healing potions may be a cheaper healing method in some situations due to some of the mobs having very strict appetites...
-A dedicated inventory slot for heal-ables would be nice, since it seems you can't keep them alive without healing them constantly currently.
-What if you added some kind of downed system? Something akin to Player Revive (mod) where instead of dying the mob is downed & can be revived on the spot within a certain time limit? (Also helps with the problem of having to pickup and reequip their gear all the time whenever they die.)

### Pathing ###
-They get stuck in water pretty easily
-If they are "angry" then they won't teleport to you even if it isn't your fault, so you either have to creature pod them or kill them to move them across long distance travel like the Waystones mod's teleporters.

### Traits / Items ###
-Kobold requiring a fork made out of netherite ingots, to find ancient debris (scraps), is a bit silly imo. If this were the only mod I was using & it required scraps to make it & not ingots maybe it would be an interesting choice, but it definitely is outclassed by other mods & choices like using the 5 netherite ingots to fully kit yourself out?... (Netherite boots, leggings, chestplate, helmet, & sword OR pickaxe.) I don't see why anyone would commit 5 full netherite ingots to their Kobold unless they outright already had enough netherite ingots that they were doing it just to mess around with their excessive wealth, everyone would undoubtedly make a full kit before committing to the netherite fork, & this is all implying the Kobold actually was tough enough to not get destroyed in the nether...

-Creeper girl being given the ability to use modded tnt would be cool, also if she had explosive resistance or immunity too that'd be neat, I tried to go caving with one once only for her to take an L to a normal creeper that snuck up on me.

### Identity ###
-Some way of identifying the abilities of the mob without opening the wiki would be nice. What if we had a page in the mob's equipment page that would let us read a brief description of their talents?
-A guidebook / in game wiki would be nice (You already said this was planned for later, just keeping it in mind).

### Things to consider ###
It might be a good idea to take a look at "rivaling" mods to get some inspiration or for considering the overall effectiveness & balance of the mobs.
-Minecraft Comes Alive Reborn is a mod that adds companions (that replace villagers) that are gained through repeated gifts, they have inventories & can be fully re-equipped & even ride horses, they can die but have a complex revival process.
-Human Companions adds companions that require specific foods before they follow you, they have an inventory but are stuck with their weapon class they started with, they can die permanently.
-Doggy Talents Next adds improved dogs that are leveled up through treats, they have a variety of special skills to equip, whenever they die they are healed on their bed before they can go out again, they do not lose progress on death, & they are revived overtime.
-Player Companions I haven't tried this one myself, but it looks interesting as well, they have special effects, & they can be resummoned with an item if killed supposedly.

**Comment by SodiumZH** [comment]
Wow, thank you so much for such comprehensive suggestions!!

After all, this mod is still in Alpha phase and I have to prioritize finishing all mobs first, so don't worry too much about numerical balance, since I will rebalance them after finishing all mobs. Also further more bauble items will be added. I design the strength of the mobs under a difficulty of vanilla minecraft with only HMaG, DWMG and Grimoire of Gaia loaded, so it does probably not fit numerically-high modpacks. Maybe I'll leave some Forge hooks (events) for other modders to extend, but not prioritized.

I'll reconsider about how to limit the size of the "mob army" with minimal hard restrictions. In earlier versions the befriending items are much more costly than now, but after testing I found it would be boring and wearing players' patience to collect items.

As for mobs' unintended death, the "Healing Jade" and "Life Jade" are designed to prevent this. The hostilities will probably also be reconsidered to reduce the random combats happening with players absent. The mob will lose half of its level (not exp) on death, e.g. if a dead mob is lvl. 28, after respawning it will be lvl. 14. Its affinity will reduce only when it died when owner is nearby, but it will be adjusted in the future.

I have to admit that the AI is still very buggy, but if it's not very serious I won't handle it immediately. Actually the concept of DWMG is totally not for more guards/soldiers. I'd like to make the mobs more like "partners" who need to sometimes **be protected** than protecting you. I'm even planning to make them more like Villagers and further reduce the importance of combat in this mod.

Befriending items and corresponding progress values were written somewhat randomly since the priority is finishing all mobs. After finishing, I'll adjust all numerical contents as described above.

Books and UI descriptions are also on my to-do list. But they aren't technically simple and don't expect them to come out quickly.

**Comment by SodiumZH** [comment]
Anyway, thanks for your suggestions and inspiritions. The current version is far not the final version, and I'll carefully consider about issues you pointed out, but it will take much time.
