### ISSUE TITLE
[1.19.2] (0.1.17.1 & 0.1.18) {Bug} Crash when getting hit during Cursed Doll taming process.

### ISSUE THREAD

**Issue by togera13** [SodiumZH/Days-with-Monster-Girls#13]
0.1.17.1:
[crash-2023-11-10_18.01.11-server.txt](https://github.com/SodiumZH/Days-with-Monster-Girls/files/13323677/crash-2023-11-10_18.01.11-server.txt)
[crash-2023-11-10_18.08.18-server.txt](https://github.com/SodiumZH/Days-with-Monster-Girls/files/13323678/crash-2023-11-10_18.08.18-server.txt)
[latest1.log](https://github.com/SodiumZH/Days-with-Monster-Girls/files/13323679/latest1.log)
[latest2.log](https://github.com/SodiumZH/Days-with-Monster-Girls/files/13323681/latest2.log)

0.1.18:
[crash-2023-11-10_18.37.25-server.txt](https://github.com/SodiumZH/Days-with-Monster-Girls/files/13323774/crash-2023-11-10_18.37.25-server.txt)
[latest.log](https://github.com/SodiumZH/Days-with-Monster-Girls/files/13323775/latest.log)
Without that other mod it suspected:
[crash-2023-11-10_18.42.36-server.txt](https://github.com/SodiumZH/Days-with-Monster-Girls/files/13323785/crash-2023-11-10_18.42.36-server.txt)
[latest2.log](https://github.com/SodiumZH/Days-with-Monster-Girls/files/13323783/latest2.log)

Also just wanted to note that I did manage to tame them after fully boxing them in since they couldn't hit me anymore; the problem is just when they _hit_ you after you have given them any wool.

**Comment by SodiumZH** [comment]
This COULD have been already fixed in a certain update (I forgot which). If the issue still exists in the latest version please reopen this.
