### ISSUE TITLE
1.20.1 Grimoire Gaia is alive again; please add support for taming!

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SodiumZH/Days-with-Monster-Girls#18]
Your mod + Grimoire Gaia = Kawai! 

If not life goes on.

**Comment by togera13** [comment]
> Your mod + Grimoire Gaia = Kawai!
> 
> If not life goes on.

I also think it would be cool if we could tame Grimoire of Gaia mobs, though that'd probably be better separated into a separate mod, but idk.

I want to tame the bee...

**Comment by SodiumZH** [comment]
I will make DwMG-Gaia, but please give me some time! There are still many things not implemented in HMaG! I do this only part-time only by myself, so don't hurry me!  o(>_<)o

**Comment by P3rf3ctXZer0** [comment]
Much Wuv <3 no hurry <3
