### ISSUE TITLE
[1.19.2] (0.1.18) Wiki suggested healing items don't work on Ghastly Seeker or wiki information is incomplete.

### ISSUE THREAD

**Issue by togera13** [SodiumZH/Days-with-Monster-Girls#20]
I can't heal the Ghastly Seeker with any of the healing items in the mod, including the ones it supposedly takes, I have been using healing splash potions in the meantime since those still work.

**Comment by SodiumZH** [comment]
I mistook the healing item list of Ghastly Seeker and it will be fixed in 0.x.19. In 0.x.18 you can heal them with items for Creeper Girls.
