### ISSUE TITLE
creeper girl texture glitch

### ISSUE THREAD

**Issue by pokthenpc** [SodiumZH/Days-with-Monster-Girls#5]
i wanted to tame a creeper girl so she would fight for me but the texture was bugged and it showed missing texture,also can you update the wiki please?

**Comment by SodiumZH** [comment]
Could you provide an image about the issue? And what's the version?

**Comment by pokthenpc** [comment]
![Screenshot 2023-05-21 125807](https://github.com/SodiumZH/Days-with-Monster-Girls/assets/134084552/e1a6ab35-a47b-4193-a649-d38437260a8b)

in version 1.19.2

**Comment by pokthenpc** [comment]
forge 43.2.0

**Comment by SodiumZH** [comment]
> ![Screenshot 2023-05-21 125807](https://user-images.githubusercontent.com/134084552/239736377-e1a6ab35-a47b-4193-a649-d38437260a8b.png)
> 
> in version 1.19.2

Is the material correct before taming? And is the mod version 0.1.2-alpha?

**Comment by SodiumZH** [comment]
This bug has been located and fixed in 1.19.2-0.1.4.
