### ISSUE TITLE
Mod does now Allow you to use Quantum Catcher from Forbidden and Arcanus

### ISSUE THREAD

**Issue by lSherozl** [SodiumZH/Days-with-Monster-Girls#6]
<img width="1278" alt="image" src="https://github.com/SodiumZH/Days-with-Monster-Girls/assets/65663746/4e0ae259-9231-438a-a840-b8803d325d87">
Every time I try to capture the tamed mob to bring somewhere else all I get is a armor placement opening up, or the mob is following or staying text, there needs to be a tool assigned to causing the tamed monster to follow or not, not the hand, as it interferes with other mods

**Comment by SodiumZH** [comment]
Fixed in 1.18.2-0.0.5 & 1.19.2-0.1.5 which are uploaded to CurseForge.

**Comment by lSherozl** [comment]
Thanks
