### ISSUE TITLE
Not sure if this is an error with your mod??

### ISSUE THREAD

**Issue by lSherozl** [SodiumZH/Days-with-Monster-Girls#7]
[crash-2023-06-24_00.16.18-server.txt](https://github.com/SodiumZH/Days-with-Monster-Girls/files/11855593/crash-2023-06-24_00.16.18-server.txt)

**Comment by lSherozl** [comment]
Yes going back to dwmg 0.1.5.1 and befriendmobs-1.19.2-0.1.5 causes me to not crash anymore

**Comment by lSherozl** [comment]
Also cant interact with banshee or get her tamed in that version above

**Comment by lSherozl** [comment]
Crashes on the second latest version too
[crash-2023-06-25_03.44.51-server.txt](https://github.com/SodiumZH/Days-with-Monster-Girls/files/11859322/crash-2023-06-25_03.44.51-server.txt)

**Comment by lSherozl** [comment]
[latest.log](https://github.com/SodiumZH/Days-with-Monster-Girls/files/11859323/latest.log)

**Comment by SodiumZH** [comment]
Did this happen on befriended mob killing a mob?

**Comment by SodiumZH** [comment]
I failed to reproduce the Banshee issue in either single- and multi-player game. 
To give items to Banshee it's required to be >=8 wither rose (blocks) around, and player must have Wither effect of any level (not including the damaging effect of Necromancer's Hat). If the conditions are fulfilled, would you be able to provide details for reproducting this issue?

**Comment by lSherozl** [comment]
> I failed to reproduce the Banshee issue in either single- and multi-player game. To give items to Banshee it's required to be >=8 wither rose (blocks) around, and player must have Wither effect of any level (not including the damaging effect of Necromancer's Hat). If the conditions are fulfilled, would you be able to provide details for reproducting this issue?

I meant no matter how many cake slices I feed the banshee, she does not get tamed in the 0.15 version of the game, while I can do that for the zombies, if you are saying you can only tame her with the wither effect, then I did not do that, so it might be that I did not tame her in the proper way. I wish there was a guide on how to tame each mob, since according to you not all of them are able to be tamed with the moon slice cake thingy

**Comment by lSherozl** [comment]
<img width="1277" alt="image" src="https://github.com/SodiumZH/Days-with-Monster-Girls/assets/65663746/7cd07b7d-5706-4e92-a3ac-dcb490bce4c4">
As you can see I can not tame her no matter what I do

**Comment by lSherozl** [comment]
I have the wither roses around and the the effect, yet I see hearts once, but there is no way to get her to stay or follow or show she is tamed 
<img width="1276" alt="image" src="https://github.com/SodiumZH/Days-with-Monster-Girls/assets/65663746/fd41b033-ef43-4fe9-979d-69c1c22ed80c">

**Comment by lSherozl** [comment]
<img width="1280" alt="image" src="https://github.com/SodiumZH/Days-with-Monster-Girls/assets/65663746/543cbf2c-ad34-4115-9b14-1cea7b8c2852">
So i figured out she is tamed, cause shes not attacking me, but there is no follow or stay option with her

**Comment by lSherozl** [comment]
When tamed she seems to just be stuck in the stay phase, does not want to move or follow, and no indicator shows whether she is staying or following 
<img width="1280" alt="image" src="https://github.com/SodiumZH/Days-with-Monster-Girls/assets/65663746/ac7a2f6b-aac5-414c-ac3e-ea3ccd35ab05">

**Comment by lSherozl** [comment]
> I failed to reproduce the Banshee issue in either single- and multi-player game. To give items to Banshee it's required to be >=8 wither rose (blocks) around, and player must have Wither effect of any level (not including the damaging effect of Necromancer's Hat). If the conditions are fulfilled, would you be able to provide details for reproducting this issue?

So that I believe is a bug with the banshee

**Comment by lSherozl** [comment]
Also I can not interact with the creeper girl and slime girl in the 0.18 version of the mod, can u please have a tutorial on how each mod is tamed somewhere

**Comment by lSherozl** [comment]
Oh I see you have got a commanding stick now, sorry I understand, but please do make a tutorial on how each mob is tamed if they are unique like the banshee was

**Comment by lSherozl** [comment]
The only issues im seeing now is, how do you give the amulets to the banshee, and creeper girls and slime girls and some of the mobs are not tameable for me

**Comment by lSherozl** [comment]
> I failed to reproduce the Banshee issue in either single- and multi-player game. To give items to Banshee it's required to be >=8 wither rose (blocks) around, and player must have Wither effect of any level (not including the damaging effect of Necromancer's Hat). If the conditions are fulfilled, would you be able to provide details for reproducting this issue?

The list of mobs that I found so far that are not tameable are the slime girl and creeper girl in the 0.18 version

**Comment by lSherozl** [comment]
I might of found another bug, 
<img width="1275" alt="image" src="https://github.com/SodiumZH/Days-with-Monster-Girls/assets/65663746/9817e191-5cde-4149-abdd-8c439b3700b0">
Feeding the ender mob the ender pie, causes her to attack you after it shows one heart, takes lot of tries to finally tame her

**Comment by SodiumZH** [comment]
> I might of found another bug, <img alt="image" width="1275" src="https://user-images.githubusercontent.com/65663746/249582389-9817e191-5cde-4149-abdd-8c439b3700b0.png"> Feeding the ender mob the ender pie, causes her to attack you after it shows one heart, takes lot of tries to finally tame her

A simple signal about how the mob responds to your actions is the particles. If the item is given successfully, there will be green star particles (like those after villager trading). If something caused the process to fail, there will bew angry particles (like when villager is attacked). 

There is a tutorial in the wiki of this repository. If the tutorial is not up-to-date, you could also see wiki/gameplay-en.md file in the repo.

Ender Executor will become hostile during the whole befriending process, and this is an intended feature. Maybe I designed it too difficult and I'll reconsider about the process in the future versions.

By the way, if there's an independent bug, please open another issue instead of adding comments to existing ones, so that I can handle and label each specific issue independently.

**Comment by lSherozl** [comment]
> > I might of found another bug, <img alt="image" width="1275" src="https://user-images.githubusercontent.com/65663746/249582389-9817e191-5cde-4149-abdd-8c439b3700b0.png"> Feeding the ender mob the ender pie, causes her to attack you after it shows one heart, takes lot of tries to finally tame her
> 
> A simple signal about how the mob responds to your actions is the particles. If the item is given successfully, there will be green star particles (like those after villager trading). If something caused the process to fail, there will bew angry particles (like when villager is attacked).
> 
> There is a tutorial in the wiki of this repository. If the tutorial is not up-to-date, you could also see wiki/gameplay-en.md file in the repo.
> 
> Ender Executor will become hostile during the whole befriending process, and this is an intended feature. Maybe I designed it too difficult and I'll reconsider about the process in the future versions.
> 
> By the way, if there's an independent bug, please open another issue instead of adding comments to existing ones, so that I can handle and label each specific issue independently.

I will do that, I just want to ask, is there no way too tame the slime girl and creeper girl, there is nothing on the wiki about them, there is also the snow canine mob, many mobs dont seem to have ways to tame them

**Comment by SodiumZH** [comment]
> > > I might of found another bug, <img alt="image" width="1275" src="https://user-images.githubusercontent.com/65663746/249582389-9817e191-5cde-4149-abdd-8c439b3700b0.png"> Feeding the ender mob the ender pie, causes her to attack you after it shows one heart, takes lot of tries to finally tame her
> > 
> > 
> > A simple signal about how the mob responds to your actions is the particles. If the item is given successfully, there will be green star particles (like those after villager trading). If something caused the process to fail, there will bew angry particles (like when villager is attacked).
> > There is a tutorial in the wiki of this repository. If the tutorial is not up-to-date, you could also see wiki/gameplay-en.md file in the repo.
> > Ender Executor will become hostile during the whole befriending process, and this is an intended feature. Maybe I designed it too difficult and I'll reconsider about the process in the future versions.
> > By the way, if there's an independent bug, please open another issue instead of adding comments to existing ones, so that I can handle and label each specific issue independently.
> 
> I will do that, I just want to ask, is there no way too tame the slime girl and creeper girl, there is nothing on the wiki about them, there is also the snow canine mob, many mobs dont seem to have ways to tame them

This mod is still in development. Slime Girl and Snow Canine are not yet supported and will be added in future versions. Mobs not listed in the wiki are not finished either. Creeper Girl is already supported and described in the wiki.
