### ISSUE TITLE
Some mobs not tameable

### ISSUE THREAD

**Issue by lSherozl** [SodiumZH/Days-with-Monster-Girls#8]
I just want to ask, is there no way too tame the slime girl and creeper girl, there is nothing on the wiki about them, there is also the snow canine mob, many mobs dont seem to have ways to tame them

**Comment by SodiumZH** [comment]
This mod hasn't been finished and Slime Girl hasn't been added yet. Creeper Girl was added in very early version and described in wiki.

**Comment by lSherozl** [comment]
> This mod hasn't been finished and Slime Girl hasn't been added yet. Creeper Girl was added in very early version and described in wiki.

Okay I will wait then for when you implemented the slime girl, creeper and snow canine mob in this mod. Thank you

**Comment by SodiumZH** [comment]
> > This mod hasn't been finished and Slime Girl hasn't been added yet. Creeper Girl was added in very early version and described in wiki.
> 
> Okay I will wait then for when you implemented the slime girl, creeper and snow canine mob in this mod. Thank you

Creeper Girl has already been added. Is there something wrong with it in your game?
